"""Generic saved entrypoint; the task program is generated by Codex policy."""
import os
from pathlib import Path
import json
import hashlib
from agent_snapshot import capture_scene, read_only_tools, task_diagnostics, native_sequence_diagnostics
import agent_snapshot
from remote_yam.aspire_code_runtime import run_generated, plain

directory=Path(os.environ['OPENFORGE_RUN_DIR'])
mode=os.environ['ASPIRE_AGENT_MODE']
TASK_RESULT=dict(task=os.environ['ASPIRE_AGENT_TASK'],status='CAPTURING_SCENE',success=False,physical_motion_calls=0)
get_task_info=lambda:dict(TASK_RESULT,reward=float(TASK_RESULT.get('success',False)))
scene=capture_scene(globals(),directory/'scene',directory=directory,record_name='initial_scene.json')
if mode=='observe':
    TASK_RESULT=dict(status='OBSERVED',success=False,physical_motion_calls=0)
elif mode=='evaluate':
    TASK_RESULT=dict(status='EVALUATING_SCENE',success=False,physical_motion_calls=0)
    source=Path(os.environ['ASPIRE_AGENT_PROGRAM']).read_text()
    task=json.loads(Path(os.environ['ASPIRE_AGENT_TASK_DEFINITION']).read_text())
    program={}
    exec(compile(source,'generated_program.py','exec'),program)
    evidence=program['evaluate'](read_only_tools(globals(),scene),task)
    if not isinstance(evidence,dict) or type(evidence.get('success')) is not bool:
        raise ValueError('evaluate must return visual evidence with a boolean success')
    TASK_RESULT=dict(status='EVALUATION_ONLY',success=evidence['success'],
        physical_motion_calls=0,source_sha256=hashlib.sha256(source.encode()).hexdigest(),
        placement_evidence=plain(evidence),
        evaluation_scope=scene['context']['snapshot_mode'])
    (directory/'task_result.json').write_text(json.dumps(TASK_RESULT,indent=2)+'\n')
else:
    tools=dict(read_only=read_only_tools(globals(),scene),
        fresh_read_only=lambda:read_only_tools(globals(),capture_scene(globals(),directory/'after',directory=directory,
            record_name='outcome_scene.json')),
        **{name:globals()[name] for name in ('plan_freespace_sequence','freespace_move','open_gripper','close_gripper')})
    TASK_RESULT=run_generated(Path(os.environ['ASPIRE_AGENT_PROGRAM']).read_text(),tools,directory,
        execute=mode=='execute',task_prompt=os.environ['ASPIRE_AGENT_TASK'])
    TASK_RESULT['native_sequence_diagnostics']=native_sequence_diagnostics(directory)
    definition=directory/'task_definition.json'
    if definition.exists():
        TASK_RESULT['generated_task_diagnostics']=task_diagnostics(json.loads(definition.read_text()))
    contract=Path(os.environ.get('ASPIRE_AGENT_CONTRACT',
        str(Path(agent_snapshot.__file__).with_name('CODE-GENERATION.md'))))
    TASK_RESULT['current_program_contract']=contract.read_text()
    (directory/'task_result.json').write_text(json.dumps(TASK_RESULT,indent=2)+'\n')
get_task_info=lambda:dict(TASK_RESULT,reward=float(TASK_RESULT.get('success',False)))
