"""Reusable RGB-D geometry; task selection and poses are generated by Codex."""
import numpy as np
from scipy.spatial.transform import Rotation


def rotation_from_rpy(rpy):
    """Native display rpy degrees to a rotation matrix."""
    return Rotation.from_euler('xyz', [-rpy[1], rpy[0], -rpy[2]-90], degrees=True).as_matrix()


def rpy_from_rotation(rotation):
    euler = Rotation.from_matrix(rotation).as_euler('xyz', degrees=True)
    return [float(euler[1]), float(-euler[0]), float(-(euler[2]+90))]


def place_on_support(block, grasp, grasp_rpy, target_xy, support_plane, place_rpy, clearance_m=.002):
    """Position a measured box on a support for a chosen grasp orientation.

    Includes rotation about the grasp site. Caller selects orientation and
    transport height; there is no task-specific tilt or destination default.
    """
    initial, final = rotation_from_rpy(grasp_rpy), rotation_from_rpy(place_rpy)
    center = np.asarray(block['top_center'])-np.array([0., 0., block['height_m']/2])
    box = np.eye(3);box[:2, :2] = block['basis']
    signs = np.array([[i,j,k] for i in (-1,1) for j in (-1,1) for k in (-1,1)])
    corners = center+(signs*np.r_[block['dimensions'],block['height_m']]/2)@box.T
    rotated = (corners-np.asarray(grasp))@initial@final.T
    relative_center = final@initial.T@(center-np.asarray(grasp))
    xy = np.asarray(target_xy)-relative_center[:2]
    z = float(np.max(plane_z(support_plane,xy+rotated[:,:2])-rotated[:,2]))+clearance_m
    return np.r_[xy,z]


class TaskBlocked(RuntimeError):
    pass


def world_points(frame):
    depth = np.asarray(frame['depth_m'], dtype=float)
    k = np.asarray(frame['K'], dtype=float)
    transform = np.asarray(frame['T_world_camera'], dtype=float)
    if (depth.ndim != 2 or k.shape != (3, 3) or transform.shape != (4, 4)
            or not np.isfinite(k).all() or not np.isfinite(transform).all()
            or min(k[0, 0], k[1, 1]) <= 0):
        raise TaskBlocked('Invalid paired RGB-D geometry')
    v, u = np.indices(depth.shape)
    points = np.stack([(u-k[0, 2])*depth/k[0, 0],
                       (v-k[1, 2])*depth/k[1, 1], depth], axis=-1)
    points = points@transform[:3, :3].T+transform[:3, 3]
    points[~np.isfinite(depth) | (depth <= 0)] = np.nan
    return points


def mask_points(points, mask):
    values = points[np.asarray(mask, dtype=bool)]
    return values[np.isfinite(values).all(axis=1)]


def fit_support(points):
    """Robust measured z=a*x+b*y+c; no nominal table-height fallback."""
    points = np.asarray(points)
    if len(points) < 3:
        raise TaskBlocked('Support plane needs at least three depth points')
    points = points[::max(1, len(points)//6000)]
    keep = np.ones(len(points), dtype=bool)
    for _ in range(5):
        xyz = points[keep]
        matrix = np.column_stack([xyz[:, :2], np.ones(len(xyz))])
        if len(xyz) < 3 or np.linalg.matrix_rank(matrix) < 3:
            raise TaskBlocked('Support plane is underconstrained')
        plane = np.linalg.lstsq(matrix, xyz[:, 2], rcond=None)[0]
        residual = np.abs(points[:, 2]-np.c_[points[:, :2], np.ones(len(points))]@plane)
        keep = residual <= max(.003, 3*float(np.median(residual)))
    return plane


def plane_z(plane, xy):
    return np.asarray(xy)@plane[:2]+plane[2]


def measure_block(points, mask, support):
    cloud = mask_points(points, mask)
    if len(cloud) < 3:
        raise TaskBlocked('Block geometry needs at least three depth points')
    upper_z = float(np.quantile(cloud[:, 2], .90))
    top = cloud[np.abs(cloud[:, 2]-upper_z) < .005]
    if len(top) < 3:
        top = cloud[np.argsort(np.abs(cloud[:, 2]-upper_z))[:3]]
    center_xy = np.median(top[:, :2], axis=0)
    _, axes = np.linalg.eigh(np.cov((top[:, :2]-center_xy).T))
    long_axis = axes[:, -1]
    short_axis = np.array([-long_axis[1], long_axis[0]])
    basis = np.column_stack([long_axis, short_axis])
    uv = (top[:, :2]-center_xy)@basis
    lo, hi = np.quantile(uv, [.01, .99], axis=0)
    dimensions = hi-lo
    center_xy += ((hi+lo)/2)@basis.T
    height = upper_z-float(plane_z(support, center_xy))
    return dict(top_center=np.r_[center_xy, upper_z], dimensions=dimensions,
                height_m=height, basis=basis, visible_samples=len(top))


def grasp_pose(block, geometry):
    axis = geometry.get('closing_axis', 'grasp_x')
    if axis not in ('grasp_x', 'grasp_y'):
        raise TaskBlocked('Unknown gripper closing-axis convention')
    legacy_offset = 'tcp_to_contact_center_m' in geometry and 'grasp_to_planner_offset_m' not in geometry
    offset = np.asarray(geometry.get('tcp_to_contact_center_m') if legacy_offset
        else geometry.get('grasp_to_planner_offset_m', [0., 0., 0.]), dtype=float)
    if offset.shape != (3,) or not np.isfinite(offset).all():
        raise TaskBlocked('Gripper frame offset must be three finite values')
    # World +Z up. Upstream YAM local X opens/closes across the short axis.
    closing = np.r_[block['basis'][:, 1], 0.]
    z = np.array([0., 0., -1.])
    if axis == 'grasp_x':
        rotation = np.column_stack([closing, np.cross(z, closing), z])
    else:
        rotation = np.column_stack([np.cross(closing, z), closing, z])
    euler = Rotation.from_matrix(rotation).as_euler('xyz', degrees=True)
    display_rpy = [float(euler[1]), float(-euler[0]), float(-(euler[2]+90))]
    contact = block['top_center'].copy()
    contact[2] -= .4*block['height_m']
    # Upstream AnyGrasp adds its planner offset. The API pose is already a
    # grasp-site pose; the model's 0.1347 m TCP offset must not be applied again.
    return contact+(-1 if legacy_offset else 1)*rotation@offset, display_rpy
